# Copyright contributors to the IBM Security Verify Directory Operator project

apiVersion: ibm.com/v1
kind: IBMSecurityVerifyDirectory
metadata:
  name: ibmsecurityverifydirectory-sample
spec:
  replicas:
    pvcs: 
    - replica-1
    - replica-2

  pods:
    image: 
      repo:            icr.io/isvd
      label:           latest

    configMap:
      proxy:   
        name: isvd-proxy-config
        key:  config.yaml
      server:  
        name: isvd-server-config
        key:  config.yaml

    serviceAccountName: isvd 

