# Copyright contributors to the IBM Security Verify Directory Operator project

apiVersion: ibm.com/v1
kind: IBMSecurityVerifyDirectory
metadata:
  labels:
    app.kubernetes.io/name: ibmsecurityverifydirectory
    app.kubernetes.io/instance: ibmsecurityverifydirectory-sample
    app.kubernetes.io/part-of: verify-directory
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: verify-directory-operator
  name: ibmsecurityverifydirectory-sample
spec:
  replicas:
  - id:  replica-1
    pvc: replica-1-pvc

  pods:
    serviceAccountName: isvd 
    image: 
      repo:    icr.io/isvd
      label:   latest
    configMap:
      proxy:   isvd-proxy-config
      server:  isvd-server-config

