# Copyright contributors to the IBM Security Verify Directory Operator project

# permissions for end users to edit ibmsecurityverifydirectories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ibmsecurityverifydirectory-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: verify-directory-operator
    app.kubernetes.io/part-of: verify-directory
    app.kubernetes.io/managed-by: kustomize
  name: ibmsecurityverifydirectory-editor-role
rules:
- apiGroups:
  - ibm.com
  resources:
  - ibmsecurityverifydirectories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibm.com
  resources:
  - ibmsecurityverifydirectories/status
  verbs:
  - get
